// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPqZmTYQiZtIMkxwHpCZk1itjV35Xrkmw',
    appId: '1:425484715672:web:f26c419e8965403fedb2ed',
    messagingSenderId: '425484715672',
    projectId: 'uas-pab2-8d97f',
    authDomain: 'uas-pab2-8d97f.firebaseapp.com',
    databaseURL: 'https://uas-pab2-8d97f-default-rtdb.firebaseio.com',
    storageBucket: 'uas-pab2-8d97f.firebasestorage.app',
    measurementId: 'G-NK2NCHG1C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlx4U4uSzyzpNJW-iWupYxGOZWW0kzaak',
    appId: '1:425484715672:android:49d8c08ea6915552edb2ed',
    messagingSenderId: '425484715672',
    projectId: 'uas-pab2-8d97f',
    databaseURL: 'https://uas-pab2-8d97f-default-rtdb.firebaseio.com',
    storageBucket: 'uas-pab2-8d97f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvFrNVuwX9zMYf2hRLbjlciCZpcvKeyk',
    appId: '1:425484715672:ios:b8ce62a4382adcf0edb2ed',
    messagingSenderId: '425484715672',
    projectId: 'uas-pab2-8d97f',
    databaseURL: 'https://uas-pab2-8d97f-default-rtdb.firebaseio.com',
    storageBucket: 'uas-pab2-8d97f.firebasestorage.app',
    iosBundleId: 'com.example.projectUasPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMvFrNVuwX9zMYf2hRLbjlciCZpcvKeyk',
    appId: '1:425484715672:ios:b8ce62a4382adcf0edb2ed',
    messagingSenderId: '425484715672',
    projectId: 'uas-pab2-8d97f',
    databaseURL: 'https://uas-pab2-8d97f-default-rtdb.firebaseio.com',
    storageBucket: 'uas-pab2-8d97f.firebasestorage.app',
    iosBundleId: 'com.example.projectUasPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPqZmTYQiZtIMkxwHpCZk1itjV35Xrkmw',
    appId: '1:425484715672:web:0ebf65f7e273ec99edb2ed',
    messagingSenderId: '425484715672',
    projectId: 'uas-pab2-8d97f',
    authDomain: 'uas-pab2-8d97f.firebaseapp.com',
    databaseURL: 'https://uas-pab2-8d97f-default-rtdb.firebaseio.com',
    storageBucket: 'uas-pab2-8d97f.firebasestorage.app',
    measurementId: 'G-WJCGV0S195',
  );
}
